version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amaoverflow-frontend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - frontend-network
    command: npm run dev

networks:
  frontend-network:
    driver: bridge