version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amaoverflow-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - backend-network
    command: npm run dev

networks:
  backend-network:
    driver: bridge